on: [pull_request]

name: CI

jobs:
  check_and_test:
    name: Check+Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: ${{ matrix.rust }}

      - name: Run cargo check
        run: cargo check

      - name: Run cargo test
        run: cargo test

  check_msrv:
    name: Check minimum rust version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.37
        with:
          components: rustfmt, clippy

      # This is needed since recent criterion versions don't build on 1.37
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Run cargo check
        run: cargo hack check --no-dev-deps

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
