on: [pull_request]

name: CI

jobs:
  check_and_test:
    name: Check+Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: ${{ matrix.rust }}

      - name: Run cargo check
        run: cargo check

      - name: Run cargo test
        run: cargo test

  check_msrv:
    name: Check minimum rust version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.61
        with:
          components: rustfmt, clippy

      - name: Run cargo check
        run: cargo check

  fmt:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
